//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceMVCClient.JobOpenings {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jobs", Namespace="http://schemas.datacontract.org/2004/07/JobOpenings")]
    [System.SerializableAttribute()]
    public partial class Jobs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobOpenings.IJobOpenings")]
    public interface IJobOpenings {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobOpenings/GetAvailbleJobList", ReplyAction="http://tempuri.org/IJobOpenings/GetAvailbleJobListResponse")]
        System.Collections.Generic.List<WebServiceMVCClient.JobOpenings.Jobs> GetAvailbleJobList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobOpenings/GetAvailbleJobList", ReplyAction="http://tempuri.org/IJobOpenings/GetAvailbleJobListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebServiceMVCClient.JobOpenings.Jobs>> GetAvailbleJobListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobOpenings/GetJobsByRole", ReplyAction="http://tempuri.org/IJobOpenings/GetJobsByRoleResponse")]
        System.Collections.Generic.List<WebServiceMVCClient.JobOpenings.Jobs> GetJobsByRole(string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobOpenings/GetJobsByRole", ReplyAction="http://tempuri.org/IJobOpenings/GetJobsByRoleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebServiceMVCClient.JobOpenings.Jobs>> GetJobsByRoleAsync(string role);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobOpeningsChannel : WebServiceMVCClient.JobOpenings.IJobOpenings, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobOpeningsClient : System.ServiceModel.ClientBase<WebServiceMVCClient.JobOpenings.IJobOpenings>, WebServiceMVCClient.JobOpenings.IJobOpenings {
        
        public JobOpeningsClient() {
        }
        
        public JobOpeningsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobOpeningsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobOpeningsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobOpeningsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WebServiceMVCClient.JobOpenings.Jobs> GetAvailbleJobList() {
            return base.Channel.GetAvailbleJobList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebServiceMVCClient.JobOpenings.Jobs>> GetAvailbleJobListAsync() {
            return base.Channel.GetAvailbleJobListAsync();
        }
        
        public System.Collections.Generic.List<WebServiceMVCClient.JobOpenings.Jobs> GetJobsByRole(string role) {
            return base.Channel.GetJobsByRole(role);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebServiceMVCClient.JobOpenings.Jobs>> GetJobsByRoleAsync(string role) {
            return base.Channel.GetJobsByRoleAsync(role);
        }
    }
}
