//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceMVCClient.CalcService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcService.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Addition", ReplyAction="http://tempuri.org/ICalculator/AdditionResponse")]
        int Addition(int firstNo, int SecondNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Addition", ReplyAction="http://tempuri.org/ICalculator/AdditionResponse")]
        System.Threading.Tasks.Task<int> AdditionAsync(int firstNo, int SecondNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Substraction", ReplyAction="http://tempuri.org/ICalculator/SubstractionResponse")]
        int Substraction(int firstNo, int SecondNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Substraction", ReplyAction="http://tempuri.org/ICalculator/SubstractionResponse")]
        System.Threading.Tasks.Task<int> SubstractionAsync(int firstNo, int SecondNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Multiplication", ReplyAction="http://tempuri.org/ICalculator/MultiplicationResponse")]
        int Multiplication(int firstNo, int SecondNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Multiplication", ReplyAction="http://tempuri.org/ICalculator/MultiplicationResponse")]
        System.Threading.Tasks.Task<int> MultiplicationAsync(int firstNo, int SecondNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Division", ReplyAction="http://tempuri.org/ICalculator/DivisionResponse")]
        decimal Division(int firstNo, int SecondNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Division", ReplyAction="http://tempuri.org/ICalculator/DivisionResponse")]
        System.Threading.Tasks.Task<decimal> DivisionAsync(int firstNo, int SecondNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : WebServiceMVCClient.CalcService.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<WebServiceMVCClient.CalcService.ICalculator>, WebServiceMVCClient.CalcService.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Addition(int firstNo, int SecondNo) {
            return base.Channel.Addition(firstNo, SecondNo);
        }
        
        public System.Threading.Tasks.Task<int> AdditionAsync(int firstNo, int SecondNo) {
            return base.Channel.AdditionAsync(firstNo, SecondNo);
        }
        
        public int Substraction(int firstNo, int SecondNo) {
            return base.Channel.Substraction(firstNo, SecondNo);
        }
        
        public System.Threading.Tasks.Task<int> SubstractionAsync(int firstNo, int SecondNo) {
            return base.Channel.SubstractionAsync(firstNo, SecondNo);
        }
        
        public int Multiplication(int firstNo, int SecondNo) {
            return base.Channel.Multiplication(firstNo, SecondNo);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicationAsync(int firstNo, int SecondNo) {
            return base.Channel.MultiplicationAsync(firstNo, SecondNo);
        }
        
        public decimal Division(int firstNo, int SecondNo) {
            return base.Channel.Division(firstNo, SecondNo);
        }
        
        public System.Threading.Tasks.Task<decimal> DivisionAsync(int firstNo, int SecondNo) {
            return base.Channel.DivisionAsync(firstNo, SecondNo);
        }
    }
}
