//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherSericeClient.WeatherService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherService.IWeatherInfo")]
    public interface IWeatherInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherInfo/celciustofarenheit", ReplyAction="http://tempuri.org/IWeatherInfo/celciustofarenheitResponse")]
        double celciustofarenheit(double temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherInfo/celciustofarenheit", ReplyAction="http://tempuri.org/IWeatherInfo/celciustofarenheitResponse")]
        System.Threading.Tasks.Task<double> celciustofarenheitAsync(double temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherInfo/farenheittocelcius", ReplyAction="http://tempuri.org/IWeatherInfo/farenheittocelciusResponse")]
        double farenheittocelcius(double temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherInfo/farenheittocelcius", ReplyAction="http://tempuri.org/IWeatherInfo/farenheittocelciusResponse")]
        System.Threading.Tasks.Task<double> farenheittocelciusAsync(double temp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeatherInfoChannel : WeatherSericeClient.WeatherService.IWeatherInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherInfoClient : System.ServiceModel.ClientBase<WeatherSericeClient.WeatherService.IWeatherInfo>, WeatherSericeClient.WeatherService.IWeatherInfo {
        
        public WeatherInfoClient() {
        }
        
        public WeatherInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double celciustofarenheit(double temp) {
            return base.Channel.celciustofarenheit(temp);
        }
        
        public System.Threading.Tasks.Task<double> celciustofarenheitAsync(double temp) {
            return base.Channel.celciustofarenheitAsync(temp);
        }
        
        public double farenheittocelcius(double temp) {
            return base.Channel.farenheittocelcius(temp);
        }
        
        public System.Threading.Tasks.Task<double> farenheittocelciusAsync(double temp) {
            return base.Channel.farenheittocelciusAsync(temp);
        }
    }
}
