//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public string Category_code { get; set; }
        public string Category_name { get; set; }
        public string Division { get; set; }
        public string Region { get; set; }
        public Nullable<int> supplier_id { get; set; }
    
        public virtual SupplierInfo SupplierInfo { get; set; }
    }
}
