//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Custid { get; set; }
        public string Custname { get; set; }
        public string CustAddress { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> Salary { get; set; }
    }
}
